# Generated by Django 3.0 on 2020-01-24 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='název')),
                ('user_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='uživatelů')),
                ('licence_till', models.DateField(blank=True, null=True, verbose_name='licence platná do')),
                ('find_alternative', models.BooleanField(verbose_name='najít alternativy')),
                ('note', models.TextField(blank=True, null=True, verbose_name='poznámka')),
                ('categories', models.ManyToManyField(related_name='_software_categories_+', to='categories.Category', verbose_name='kategorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to=settings.AUTH_USER_MODEL, verbose_name='kategorie')),
            ],
            options={
                'verbose_name': 'software',
                'verbose_name_plural': 'software',
            },
        ),
    ]
