# Generated by Django 3.0 on 2020-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='user_count',
        ),
        migrations.AddField(
            model_name='software',
            name='licence_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='počet licencí'),
        ),
        migrations.AddField(
            model_name='software',
            name='licence_type',
            field=models.CharField(blank=True, choices=[('PERPETUAL', 'perpetual'), ('SUBSCRIPTION', 'subscription')], max_length=32, null=True, verbose_name='typ licence'),
        ),
        migrations.AddField(
            model_name='software',
            name='licence_unit',
            field=models.CharField(blank=True, choices=[('USER', 'počet uživatel'), ('DEVICE', 'počet zařízení'), ('HW', 'počet jader / RAM'), ('OTHER', 'jiné')], max_length=32, null=True, verbose_name='metrika licence'),
        ),
        migrations.AddField(
            model_name='software',
            name='need_customization',
            field=models.BooleanField(default=False, verbose_name='potřeba cusomizace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='need_extension',
            field=models.BooleanField(default=False, verbose_name='potřeba rozšíření'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='need_upgrade',
            field=models.BooleanField(default=False, verbose_name='potřeba ugprade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='watch_expiration',
            field=models.BooleanField(default=False, verbose_name='hlídat expiraci'),
            preserve_default=False,
        ),
    ]
