# Generated by Django 3.0 on 2020-02-28 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20200204_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
