image: python:3.7

services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: directit
  POSTGRES_USER: directit
  POSTGRES_PASSWORD: directit
  REDIS_URL: redis://redis:6379/0
  DEFAULT_FROM_EMAIL: info@directit.cz
  DEFAULT_NOTIFICATION_EMAIL: info@directit.cz
  PROJECT_MAIN_DOMAIN: gitlab.directit.cz

  # Change pip's cache directory to be inside the project directory since we can
  # only cache local items.
  # PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
#cache:
#  paths:
#    - .cache/pip
#    - .venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install -r requirements/testing.pip

stages:
  - lint
  - test

lint:
  script:
    - flake8 main/

test:
  script:
    - python manage.py test --settings=main.settings.gitlab_settings
