# Generated by Django 3.0 on 2021-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='název služby')),
                ('time_duration', models.CharField(blank=True, max_length=255, verbose_name='časová náročnost')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('milestone', models.IntegerField(choices=[(1, 'milník 1'), (2, 'milník 2'), (3, 'milník 3'), (4, 'milník 4')])),
                ('category', models.CharField(choices=[('ANALYZE', 'Analýzy & Studie'), ('SERVICE', 'ICT služby'), ('CONSULTANT', 'Konzultanti a Specialisté')], max_length=32, verbose_name='typ služby')),
            ],
            options={
                'verbose_name': 'služba',
                'verbose_name_plural': 'služby',
            },
        ),
    ]
