# Generated by Django 3.0 on 2021-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, help_text='https://vue.architectui.com/architectui-vue-pro/#/elements/icons', max_length=32),
        ),
    ]
