# Generated by Django 3.0 on 2019-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='název')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='obrázek')),
                ('categories', models.ManyToManyField(blank=True, to='categories.Category', verbose_name='kategorie')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tagy',
            },
        ),
    ]
