from django.utils.translation import ugettext_lazy as _

COMPANY_ROLE_CONSULTANT = 'CONSULTANT'
COMPANY_ROLE_SUPPLIER = 'SUPPLIER'
COMPANY_ROLE_CLIENT = 'CLIENT'

COMPANY_ROLE_CHOICES = (
    (COMPANY_ROLE_CONSULTANT, _("konzultant")),
    (COMPANY_ROLE_SUPPLIER, _('dodavatel')),
    (COMPANY_ROLE_CLIENT, _('client')),
)


PROFILE_FREE = 'FREE'
PROFILE_BASIC = 'BASIC'
PROFILE_PREMIUM = 'PREMIUM'
PROFILE_CHOICES = (
    (PROFILE_FREE, 'FREE'),
    (PROFILE_BASIC, 'BASIC'),
    (PROFILE_PREMIUM, 'PREMIUM'),
)
