# Generated by Django 3.0 on 2020-05-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'kategorie', 'verbose_name_plural': 'kategorie'},
        ),
    ]
