PROJECT_STEP_NOT_DEMAND = 0
PROJECT_STEP_DEMAND = 10
PROJECT_STEP_IN_PROGRESS = 20
PROJECT_STEP_COMPLETED = 30

PROJECT_STEP_CHOICES = (
    (PROJECT_STEP_NOT_DEMAND, 'neřešeno'),
    (PROJECT_STEP_DEMAND, 'požadováno'),
    (PROJECT_STEP_IN_PROGRESS, 'ropracováno'),
    (PROJECT_STEP_COMPLETED, 'dokončeno'),
)

PROJECT_STATUS_NEW = 0
PROJECT_STATUS_HOLD = 10
PROJECT_STATUS_IN_PROGRESS = 20
PROJECT_STATUS_COMPLETED = 30

PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_NEW, 'nový'),
    (PROJECT_STATUS_HOLD, 'pozastaveno'),
    (PROJECT_STATUS_IN_PROGRESS, 'probíhá'),
    (PROJECT_STATUS_COMPLETED, 'dokončeno'),
)
