# Generated by Django 3.0 on 2020-01-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191223_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gps_lat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='GPS lat'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gps_lng',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='GPS lng'),
        ),
    ]
