# Generated by Django 3.0 on 2020-01-15 13:30

from django.db import migrations
import main.apps.companies.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200113_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=main.apps.companies.utils.company_dir_path, verbose_name='obrázek'),
        ),
    ]
