# Generated by Django 3.0 on 2020-06-09 08:43

from django.conf import settings
from django.db import migrations, models
import main.apps.companies.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_auto_20200115_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.apps.companies.utils.company_dir_path, verbose_name='obrázek'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='companies', through='companies.UserCompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
