# Generated by Django 3.0 on 2020-06-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200609_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'obchodní subjekt', 'verbose_name_plural': 'obchodní subjekty'},
        ),
    ]
