# Generated by Django 3.0 on 2020-11-19 15:06

from django.db import migrations, models


def set_plan(apps, schema):
    Company = apps.get_model('companies.Company')
    Company.objects.all().update(plan='BASIC')


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20200609_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('FREE', 'FREE'), ('BASIC', 'BASIC'), ('PREMIUM', 'PREMIUM')], default='FREE', max_length=32, verbose_name='Profil'),
        ),
        migrations.RunPython(set_plan)
    ]
