# Generated by Django 3.0 on 2021-04-14 12:53

from django.db import migrations, models


def first_letter_in_word(value: str) -> str:
    str_list = value.split(" ")

    if len(str_list) > 1:
        return str_list[0] + " {}*****".format(str_list[1][0] if len(str_list[1]) > 0 else "")
    if len(str_list) == 1:
        return str_list[0] + " *****"
    else:
        return "******"


def copy_public_name(apps, schema):
    Company = apps.get_model('companies.Company')
    for c in Company.objects.all():
        if c.role == 'CONSULTANT':
            c.name_public = first_letter_in_word(c.name)
        else:
            c.name_public = c.name
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_d_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_public',
            field=models.CharField(db_index=True, default='', max_length=512, verbose_name='obchodní název publikovatelný'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_public_name)
    ]
