# Generated by Django 3.0 on 2020-01-21 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_auto_20200115_1330'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('rating', models.PositiveSmallIntegerField(null=True, verbose_name='hodnocení')),
                ('text', models.TextField(blank=True, null=True, verbose_name='slovní hodnocení')),
                ('authorized', models.BooleanField(default=False, verbose_name='autorizováno')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='jaké společnosti')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='od uživatele')),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'reference',
            },
        ),
    ]
