# Generated by Django 3.0 on 2021-03-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_company_d_tags'),
        ('tags', '0002_auto_20200519_1057'),
        ('vendors', '0001_initial'),
        ('categories', '0002_auto_20200519_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='categories.Category')),
                ('suppliers', models.ManyToManyField(blank=True, related_name='products', to='companies.Company')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='tags.Tag')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.Vendor')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
            },
        ),
    ]
