# Generated by Django 3.0 on 2021-03-18 11:25

from django.db import migrations, models
import main.apps.products.utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.apps.products.utils.product_dir_path, verbose_name='logo'),
        ),
    ]
