# Generated by Django 3.0 on 2021-03-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
        ('products', '0002_auto_20210304_0951'),
    ]

    operations = [
    ]
