# Generated by Django 3.0 on 2021-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200721_1209'),
        ('reference', '0002_auto_20210611_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='references', to='files.File'),
        ),
        migrations.AddField(
            model_name='reference',
            name='sector',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bankovnictví, Finanční služby'), (2, 'Energetika'), (3, 'Informační technologie'), (4, 'Kultura'), (5, 'Lesnictví, těžba'), (6, 'Logistika, Transport'), (7, 'Média'), (8, 'Retail, Obchod'), (9, 'Služby'), (10, 'Stavebnictví'), (11, 'Telekomunikace'), (12, 'Turistický ruch, Pohostinství'), (13, 'Veřejný sektor'), (14, 'Výrobní průmysl'), (15, 'Vzdělávání'), (16, 'Zábavní průmysl'), (17, 'Zdravotnictví, Farmaceutický Průmysl'), (18, 'Zemědělství, Potravinářství'), (19, 'Ostatní')], default=1),
            preserve_default=False,
        ),
    ]
