BUSSINES_SECTOR_CHOICES = (
    (1, "Bankovnictví, Finanční služby"),
    (2, "Energetika"),
    (3, "Informační technologie"),
    (4, "Kultura"),
    (5, "Lesnictví, těžba"),
    (6, "Logistika, Transport"),
    (7, "Média"),
    (8, "Retail, Obchod"),
    (9, "Služby"),
    (10, "Stavebnictví"),
    (11, "Telekomunikace"),
    (12, "Turistický ruch, Pohostinství"),
    (13, "Veřejný sektor"),
    (14, "Výrobní průmysl"),
    (15, "Vzdělávání"),
    (16, "Zábavní průmysl"),
    (17, "Zdravotnictví, Farmaceutický Průmysl"),
    (18, "Zemědělství, Potravinářství"),
    (19, "Ostatní"),
)
