# Generated by Django 3.0 on 2020-01-15 11:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('callback_type', models.CharField(choices=[('SURVEY', 'průzkum trhu'), ('REFERENCE', 'nezávislá reference'), ('OTHER', 'ostatní')], max_length=128, verbose_name='typ')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='jméno')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=255, null=True, region=None, verbose_name='telefon')),
                ('time', models.TimeField(null=True, verbose_name='Vhodný čas pro hovor')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
