# Generated by Django 3.0 on 2020-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0002_callbackrequest_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='callback_type',
            field=models.CharField(choices=[('SURVEY', 'průzkum trhu'), ('REFERENCE', 'nezávislá reference'), ('CONSULTATION', 'konzultace k vybranému projektu '), ('EXPERTIZE', 'expertní názor'), ('OTHER', 'ostatní')], max_length=128, verbose_name='typ'),
        ),
    ]
