# Generated by Django 3.0 on 2020-02-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbacks', '0003_auto_20200204_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackrequest',
            name='callback_type',
            field=models.CharField(blank=True, choices=[('SURVEY', 'průzkum trhu'), ('REFERENCE', 'nezávislá reference'), ('CONSULTATION', 'konzultace k vybranému projektu '), ('EXPERTIZE', 'expertní názor'), ('OTHER', 'ostatní')], max_length=128, null=True, verbose_name='typ'),
        ),
    ]
