# Generated by Django 3.0 on 2021-04-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200519_1057'),
        ('callbacks', '0004_auto_20200214_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
