# Generated by Django 3.0 on 2020-06-09 08:05

from django.db import migrations, models


def migrate_data(apps, schema):
    Project = apps.get_model('projects.Project')
    for p in Project.objects.all():
        if p.step1:
            p.step1int = 10
        if p.step2:
            p.step2int = 10
        if p.step3:
            p.step3int = 10
        if p.step4:
            p.step4int = 10
        if p.step5:
            p.step5int = 10
        if p.step6:
            p.step6int = 10


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200519_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'nový'), (10, 'pozastaveno'), (20, 'probíhá'), (30, 'dokončeno')], default=0, verbose_name='status projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='step1int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neřešeno'), (10, 'požadováno'), (20, 'ropracováno'), (30, 'dokončeno')], default=0, verbose_name='Definice projektu'),
        ),
        migrations.AddField(
            model_name='project',
            name='step2int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neřešeno'), (10, 'požadováno'), (20, 'ropracováno'), (30, 'dokončeno')], default=0, verbose_name='Základní návrh řešení'),
        ),
        migrations.AddField(
            model_name='project',
            name='step3int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neřešeno'), (10, 'požadováno'), (20, 'ropracováno'), (30, 'dokončeno')], default=0, verbose_name='Studie trhu'),
        ),
        migrations.AddField(
            model_name='project',
            name='step4int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neřešeno'), (10, 'požadováno'), (20, 'ropracováno'), (30, 'dokončeno')], default=0, verbose_name='Oslovení dodavatelů'),
        ),
        migrations.AddField(
            model_name='project',
            name='step5int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neřešeno'), (10, 'požadováno'), (20, 'ropracováno'), (30, 'dokončeno')], default=0, verbose_name='Testování a Finální Selekce'),
        ),
        migrations.AddField(
            model_name='project',
            name='step6int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'neřešeno'), (10, 'požadováno'), (20, 'ropracováno'), (30, 'dokončeno')], default=0, verbose_name='Implementace'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='project',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='step3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='step4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='step5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='step6',
        ),

    ]
