# Generated by Django 3.0 on 2020-06-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200609_0843'),
        ('projects', '0004_auto_20200609_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='companies.Company'),
        ),
    ]
