# Generated by Django 3.0 on 2020-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('projects', '0005_project_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='projects', to='files.File'),
        ),
    ]
