# Generated by Django 3.0 on 2020-12-29 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_d_tags'),
        ('projects', '0006_project_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_projects', to='companies.Company'),
        ),
    ]
